### ISSUE TITLE
Using Spring UI in other Antora projects

### ISSUE THREAD

**Issue by oddhack** [spring-io/antora-ui-spring#105]
I'm wondering if this UI is usable with other Antora sites without disproportionate effort (compared to using the Antora default UI, say) - do you folks know of any experience with this, or reasons that your UI would be hard to repurpose?

**Comment by rwinch** [comment]
The project is not deliberately built for others to reuse. That said, we built our UI from the default Antora UI & it is possible to use it/customize it in the same ways you would the default Antora UI.

**Comment by oddhack** [comment]
Thanks! Will give it a try - adding a Night Mode myself looked like a great deal of effort.
