### ISSUE TITLE
Add a project dependent water mark

### ISSUE THREAD

**Issue by schauder** [spring-io/antora-ui-spring#106]
All the documentation of the various Spring projects look really similar (which is a good thing) and there will be lots of linking between projects (I hope). This can make it somewhat difficult to see at which projects documentation I'm looking. I therefore think it would be nice to have some kind of watermark on every page, that represents the project. It could be a large so it is easy to see,
yet pale/dark green or light/dark grey depending on the style to be not obtrusive.

**Comment by oodamien** [comment]
Breadcrumbs and sidebar title are always visible now - (project title is present)
