### ISSUE TITLE
Find in page finds hidden text from the nav bar

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/antora-ui-spring#116]
Finding `Spring Boot` in https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-config/static-resources.html#page-title shows two matches but only one is visible. The unwanted match appears to be the `Spring Boot` entry in the nav bar's `Projects` drop-down. I'm on macOS. The problem occurs with both Safari and Chrome.

**Comment by wilkinsona** [comment]
Both problems described above are still there in macOS Safari and Chrome.

**Comment by oodamien** [comment]
The invisible match is in the navigation (Project > Spring Boot)

**Comment by wilkinsona** [comment]
Yeah. Can we get rid of it somehow please?
