### ISSUE TITLE
Improve Related projects on versions modal

### ISSUE THREAD

**Issue by oodamien** [spring-io/antora-ui-spring#123]
All spring projects listed

<img width="908" alt="image" src="https://github.com/spring-io/antora-ui-spring/assets/487067/9f7e6fe8-821d-480e-96c0-2a0e893c2737">

**Comment by spencergibb** [comment]
Is there a timeline for this? Hoping to have it ready for when spring cloud goes GA shortly after [Spring Boot 3.2](https://github.com/spring-projects/spring-boot/milestone/308) towards the end of November. 

![image](https://github.com/spring-io/antora-ui-spring/assets/594085/efc16164-6ff2-4f90-986c-a4e092d1d0ac)

**Comment by rwinch** [comment]
This is fixed via 34bfa04c3e7697b0e304b053df54dfc4720cae8d
