### ISSUE TITLE
Incorrect URL for Spring Cloud Commons from the "..." site versions menu

### ISSUE THREAD

**Issue by jkonicki** [spring-io/antora-ui-spring#169]
The link to Spring Cloud Commons should be `https://docs.spring.io/spring-cloud-commons/reference/` not `https://docs.spring.io/spring-cloud-commons/reference/spring-cloud-commons/` which currenly brings the users to a directory listing.

https://github.com/spring-io/antora-ui-spring/blob/6cc8933c96b77148b52e86cb63b7a74b51885c74/src/partials/version.hbs#L39

**Comment by rwinch** [comment]
Thanks for the issue. This is fixed via 34bfa04c3e7697b0e304b053df54dfc4720cae8d
