### ISSUE TITLE
Strict text wrapping in table splits words

### ISSUE THREAD

**Issue by rstoyanchev** [spring-io/antora-ui-spring#172]
Based on an issue internally reported by @jxblum, there is a text wrapping problem visible in the docs for Spring Framework, specifically the table on [Controller Method Arguments](https://docs.spring.io/spring-framework/reference/6.1/web/webmvc/mvc-controller/ann-methods/arguments.html).

![image](https://github.com/spring-io/antora-ui-spring/assets/401908/fa126998-87c4-40c1-9c94-b104243079db)

Originally observed on Google Chrome and Safari on Mac. I confirm the same with Chromium on Linux. 

The corresponding source for the table is here:

https://raw.githubusercontent.com/spring-projects/spring-framework/main/framework-docs/modules/ROOT/pages/web/webflux/controller/ann-methods/arguments.adoc

**Comment by sbrannen** [comment]
Potentially related discussion on Twitter: https://twitter.com/mojavelinux/status/1537863360040972288

**Comment by sbrannen** [comment]
It appears that this has already been addressed, since the word splitting no longer seems to occur here: https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-methods/arguments.html
