### ISSUE TITLE
`Cannot read properties of undefined` after upgrading to 0.4.4

### ISSUE THREAD

**Issue by mp911de** [spring-io/antora-ui-spring#181]
The Antora build fails with:

```
[11:09:54.851] FATAL (antora): Cannot read properties of undefined (reading 'length') in UI template partials/article-spring-projects.hbs
    type: "Error"
```
Also, upgraded to `@springio/antora-extensions@1.8.0`

**Comment by rwinch** [comment]
I believe this was fixed as part of https://github.com/spring-io/antora-ui-spring/issues/186 and https://github.com/spring-io/antora-ui-spring/issues/185 Did you try upgrading to antora-ui-spring 0.4.7?

**Comment by mp911de** [comment]
Upgrading to 0.4.7 no longer fails with the error, so closing this one.
