### ISSUE TITLE
Change body-font-weight-bold to be more bold

### ISSUE THREAD

**Issue by jvalkeal** [spring-io/antora-ui-spring#195]
Antora's default ui made this change a few weeks ago https://gitlab.com/antora/antora-ui-default/-/commit/41211f75322c45942837413b59173f05f310d3f2.

https://github.com/spring-io/antora-ui-spring/blob/6dd9ccead5a92bc5e129cc4113f2392748846b2f/src/css/vars.css#L46

Essentially value `500` is not bold enough.

**Comment by sbrannen** [comment]
For reference, the `Name` and `Description` headers in the following table should be bold.

https://docs.spring.io/spring-framework/reference/appendix.html#appendix-spring-properties
