### ISSUE TITLE
Use higher font weight for code in headlines

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/antora-ui-spring#212]
Current (font weight 400):
<img width="522" alt="Screenshot 2024-03-05 at 08 28 27" src="https://github.com/spring-io/antora-ui-spring/assets/128577/655a9eba-14a4-4657-8a80-102750d470ad">

Suggested (700)
<img width="518" alt="Screenshot 2024-03-05 at 08 28 34" src="https://github.com/spring-io/antora-ui-spring/assets/128577/49943c59-64d2-45da-91e6-6de2eead2aba">

**Comment by philwebb** [comment]
I already had some updates for code headers in #206. I just tweaked them to increase the font weight:

<img width="445" alt="Screenshot 2024-03-05 at 12 23 19 AM" src="https://github.com/spring-io/antora-ui-spring/assets/519772/3b721216-8408-4e2e-8a51-8a77f6014cf0">

**Comment by oodamien** [comment]
Fixed in https://github.com/spring-io/antora-ui-spring/pull/206.
