### ISSUE TITLE
Anchor hash “attached” to headline in Firefox

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/antora-ui-spring#213]
Firefox:
<img width="558" alt="Screenshot 2024-03-05 at 08 30 55" src="https://github.com/spring-io/antora-ui-spring/assets/128577/37d50db3-edf0-45ab-a02d-13da6eeaf4b7">

Chrome / Safari:
<img width="503" alt="Screenshot 2024-03-05 at 08 30 38" src="https://github.com/spring-io/antora-ui-spring/assets/128577/c9ae07f0-d936-44da-bc53-661ff2911ce6">

I think the latter looks better.

**Comment by philwebb** [comment]
#206 might fix this

**Comment by oodamien** [comment]
Fixed in https://github.com/spring-io/antora-ui-spring/pull/206.
