### ISSUE TITLE
Visually distinguish captions from floating text

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/antora-ui-spring#224]
Example and image captions are currently not visually distinguished from floating text as the `--caption-font-style` variable is not set.

## Current
<img width="50%" alt="Screenshot 2024-04-10 at 21 11 43" src="https://github.com/spring-io/antora-ui-spring/assets/128577/bdfec4ef-1039-4849-aa15-393defff698a">

## Suggested
(`--caption-font-style` set to `italic`)
<img width="50%" alt="Screenshot 2024-04-10 at 21 11 17" src="https://github.com/spring-io/antora-ui-spring/assets/128577/2a591dc7-1b85-4059-a5b0-963fb90e8b2b">

**Comment by oodamien** [comment]
Already address.
