### ISSUE TITLE
Breadcrumbs hidden when scrolling through code blocks

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/antora-ui-spring#256]
It looks like something is broken regarding the z-index in the relationship of paragraphs, code samples and the breadcrumb bar. When scrolling, the paragraphs are hidden by the breadcrumbs, but the code blocks hide the breadcrumb bar.

https://github.com/spring-io/antora-ui-spring/assets/128577/56fa1431-35ec-4eb1-9c33-90c526aa36e9

**Comment by oodamien** [comment]
Fixed for v0.4.16
https://github.com/spring-io/antora-ui-spring/commit/1187c38f092d017a0b17a3305390cc5a54ed8911
