### ISSUE TITLE
Asciinema casts are not rendered in latest ui bundle versions

### ISSUE THREAD

**Issue by Klopfy** [spring-io/antora-ui-spring#264]
I have noticed that some spring documentation does not display asciinema cast properly anymore.

## Not working example with spring-shell doc
- [documentation link](https://docs.spring.io/spring-shell/reference/tui/views/progress.html#_customisation) / [source code](https://github.com/spring-projects/spring-shell/blob/v3.3.1/spring-shell-docs/modules/ROOT/pages/tui/views/progress.adoc#customisation)
- Spring shell uses the [latest](https://github.com/spring-projects/spring-shell/blob/v3.3.1/spring-shell-docs/antora-playbook.yml#L42) antora-ui-spring bundle

### Screenshot
<img width="864" alt="Screenshot 2024-08-03 at 11 23 02 PM" src="https://github.com/user-attachments/assets/d928007f-ad6d-4d63-adeb-27534483af8f">

<br/><br/>
 
## Working example with spring-cli doc
- [documentation link](https://docs.spring.io/spring-cli/reference/howto/create-application.html#initializr) / [source code](https://github.com/spring-projects/spring-cli/blob/v0.9.0/docs/modules/ROOT/pages/howto/create-application.adoc#create-using-startspringio)
- Spring cli uses the [v0.4.7](https://github.com/spring-projects/spring-cli/blob/v0.9.0/docs/antora-playbook.yml#L41
) of antora-ui-spring bundle
### Screenshot
<img width="1000" alt="Screenshot 2024-08-03 at 11 23 44 PM" src="https://github.com/user-attachments/assets/f94a9b52-4c3c-491f-9918-217ceca881bd">

When trying to use asciinema extension on my end:
- using antora-ui-spring bundle, it seems to be working up until v0.4.10 and then breaks after v.0.4.11.
- using my own bundle, I have the same non-rendered cast issue. Not sure if the issue is on the bundle side or on the extension itself.

**Comment by jvalkeal** [comment]
I'm not yet sure on which side to fix it(ui or extension). Player is there but its width ends up having zero width. Essentially styling gets broken.

**Comment by Klopfy** [comment]
If it helps on the decision, I do have the very same on my own antora UI bundle (width: 0px;). I forked [antora-ui-default](https://gitlab.com/antora/antora-ui-default) one year ago and made some minor css change.
Not sure if I introduced the same conflicting element as spring ui bundle.

**Comment by jvalkeal** [comment]
So what happened is a `videoblock` in:
```
<div class="videoblock">
<div class="content"><div id="7eaf8fd0409a6c92c72f93d72ca50bcb" style=" "></div></div>
</div>
```
I added that so that the container could be styled by a user. `0.4.11` added styling for that block and that somehow broke asciinema's automatic size calculation. We now get something like:

```
.doc .imageblock, .doc .videoblock {
    align-items: center;
    display: flex;
    flex-direction: column;
}
```

It looks to be `flex` confusing asciinema.
