### ISSUE TITLE
Stay on the same page when switching version

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/antora-ui-spring#269]
Would it be possible to improve the version picker in the Antora-based docs so that you stay on the same page when changing version? For example, if I'm looking at https://docs.spring.io/spring-boot/3.4-SNAPSHOT/maven-plugin/getting-started.html and then switch to the 3.3.4 docs, I'd like to go to https://docs.spring.io/spring-boot/maven-plugin/getting-started.html but right now I get dumped back at https://docs.spring.io/spring-boot/index.html. When the same page doesn't exist across the two versions, going back to the root feels fine to me, but when it does exist in both versions, it's a bit of a pain to have to navigate back to the same page after you've changed version.

**Comment by rwinch** [comment]
It's worth noting that [Antora docs](https://docs.antora.org/antora/3.0/page/partials/) preserves the page when you select the version from the drop down in the upper right near "Edit this Page". However, it does not preserve the version when selecting the version on the lower left. I think that we just need to update the logic in our custom UI to match that of the version selector in the upper right.
