### ISSUE TITLE
Right navigation compresses center content needlessly

### ISSUE THREAD

**Issue by spencergibb** [spring-io/antora-ui-spring#29]
![image](https://user-images.githubusercontent.com/594085/134401736-04e48c19-803f-4c53-aab3-c39f923c5c10.png)

I'm on firefox on linux

**Comment by rwinch** [comment]
@spencergibb Thanks again for the report!

@oodamien Any chance you could take a look at this one?

**Comment by oodamien** [comment]
Sure
