### ISSUE TITLE
Update to algoliasearch 4

### ISSUE THREAD

**Issue by rwinch** [spring-io/antora-ui-spring#61]
We should migrate from algoliasearch 3 to algoliasearch 4 See https://www.algolia.com/doc/api-client/getting-started/update/javascript/?client=javascript

**Comment by mojavelinux** [comment]
The challenge is that the new client has a completely different interaction model and search result display that is not at all compatible with customized client adapter currently being used. In other words, it means developing the customizations from scratch. I'm also not very keen on how it now displays results. You can find examples as https://www.gatsbyjs.com/docs/ and https://docs.rubocop.org/rubocop/index.html I think something very fundamental was lost in translation.
