### ISSUE TITLE
Cookies in the bottom footer looks like a link and is not

### ISSUE THREAD

**Issue by rwinch** [spring-io/antora-ui-spring#80]
I'm honestly not sure what to do with this. It appears that [spring.io](http://spring.io/) has the ability to toggle it's cookie usage based upon some settings (which is likely also a cookie?). We do not have that functionality for the Antora site (nor did we have it for the asciidoc sites).
Perhaps the best approach is to remove that link.

cc @mminella

**Comment by oodamien** [comment]
See https://github.com/spring-io/antora-ui-spring/issues/231
