### ISSUE TITLE
What looks like duplicate search result items

### ISSUE THREAD

**Issue by rstoyanchev** [spring-io/antora-ui-spring#84]
Testing the new instasearch UI with the Spring Framework, if I enter "CORS" I get:
![image](https://github.com/spring-io/antora-ui-spring/assets/401908/825832f3-5828-455c-8788-5386ed885438)

The 1st and the 3rd link both point to the same URL [webmvc-cors.html#mvc-cors-global](https://docs.spring.io/spring-framework/reference/web/webmvc-cors.html#mvc-cors-global). Likewise the 2nd and 4th point to [webflux-cors.html#webflux-cors-global](https://docs.spring.io/spring-framework/reference/web/webflux-cors.html#webflux-cors-global), and there is more of that in the items that follow.

This may end up being related to #82, for example if it matches once the section heading, and once in the text of the 1st paragraph, but both end up being displayed in the same way:
![image](https://github.com/spring-io/antora-ui-spring/assets/401908/1cc288f8-67d3-46b1-aace-85c70cfdc9c5)

**Comment by oodamien** [comment]
@rstoyanchev Are you playing in the time with an old implementation?
Seems specific to Linux/Chrome.

**Comment by rstoyanchev** [comment]
I was using https://github.com/rwinch/spring-framework/tree/ui-snapshot, which seems to [point to latest ui-bundle](https://github.com/rwinch/spring-framework/blob/4e7a61da7075dcb6ce5a070ef804369ba64be509/antora-playbook.yml#L41). This was last night around the time I created the issue.

**Comment by rstoyanchev** [comment]
Is it not possible that it's due to "CORS" matching once the section heading, and once in the text of the 1st paragraph? So both legitimate matches that are very close to each other, but it's hard to see that from the amount of context provided.
