### ISSUE TITLE
Font weight on spring docs is insufficient in some cases

### ISSUE THREAD

**Issue by Tristan971** [spring-io/antora-ui-spring#86]
I come here on suggestion from @rwinch in https://twitter.com/rob_winch/status/1656847289690779648

In the case of my OS+display (Windows 11, 1440p 27" display) and browsers (Edge 113, Chrome 114, Firefox 114), the font used in the Spring reference documentation (ie at: https://docs.spring.io/spring-framework/reference/) feels very thin, to the point where it is rather hard to read.

Note that the sample demo of antora (ie https://antora.gitlab.io/antora-ui-default/) is *not* affected and looks just fine.

However, here's how Spring's docs render for me (it's definitely necessary to open the image fully to see the issue):

On Chrome:
![2023-05-12 03_30_17](https://github.com/spring-io/antora-ui-spring/assets/875533/382c6bea-3fc8-438d-9d5d-7600e6876dbb)

<details>
<summary>and on Firefox (ie it's not a browser-specific issue)</summary>

![2023-05-12 03_29_04](https://github.com/spring-io/antora-ui-spring/assets/875533/0ed0fc2d-b034-46dc-98bb-02af6742273f)

</details>

For comparison, here's how the antora docs render (ie it's definitely not some globally misconfigured ClearType or something):
<details>
<summary>Chrome</summary>

![2023-05-12 03_31_24](https://github.com/spring-io/antora-ui-spring/assets/875533/8ede472f-2340-43ee-b0a2-960da59413e9)

</details>

(and FF behaves the same for antora)

By fiddling a bit with the CSS, the issue stems from the `font-weight` being set to 300, which corresponds to thin rather than regular (400).
And Windows' (notoriously poor) font rendering does a very bad job with that (obnoxious hinting that looks like aliasing, mainly). Of course it looks great on my phone on the other hand, but I tend to open the Spring reference docs on my computer :-)

Anyway, once I remove the font-weight override, it is readable again:

![2023-05-12 03_42_28](https://github.com/spring-io/antora-ui-spring/assets/875533/1bc90049-4bda-4952-8367-92f0c98b7d47)

Either way, I wouldn't have assumed that this was the right place to mention this, but here it is as Rob suggested.

**Comment by rwinch** [comment]
Thanks for creating the detailed ticket @Tristan971! This is indeed the correct place. I'm assigning this to @oodamien 

I'm curious how the rest of spring.io looks to you? Do you have problems reading blog posts? https://spring.io/blog/2023/05/11/spring-framework-reference-documentation-update

**Comment by Tristan971** [comment]
The blog posts are fine on my end (though looking at their CSS they are using font-weight 400, so it's not a big surprise)

![2023-05-12 03_49_00](https://github.com/spring-io/antora-ui-spring/assets/875533/3e2ddbf9-4ee6-4e61-ae12-b147cecfcef3)

**Comment by Tristan971** [comment]
Just for the record, this isn't a new issue (ie it was there *before* the migration to Antora). It's just a long-standing unfortunate situation with thin fonts and Windows.

**Comment by rwinch** [comment]
Thanks for the follow ups!
